if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type")
endif()

set(CMAKE_EXECUTABLE_SUFFIX ".exe")
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".exe")
set(CMAKE_EXECUTABLE_SUFFIX_C ".exe")
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".exe")

set(ADD_OPTS "-DUSE_OLD_COMPILER")
if(CMAKE_SYSTEM_NAME STREQUAL "DOS")
    set(ADD_OPTS "-bt=dos ${ADD_OPTS}")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(ADD_OPTS "-bt=nt ${ADD_OPTS}")
endif()
# set(TOOLCHAIN_USE_CCWRAP 1)
if(TOOLCHAIN_USE_CCWRAP)
    set(CCWRAP_DIR "${CMAKE_CURRENT_LIST_DIR}/../thirdparty/ccwrap")
    if(EXISTS "${CCWRAP_DIR}" AND IS_DIRECTORY "${CCWRAP_DIR}")
      set(ADD_OPTS "-I${CCWRAP_DIR}/watcom/ -I${CCWRAP_DIR}/ccwrap/ -DCCWRAP_NO_EXCEPTIONS -fi=${CCWRAP_DIR}/watcom/ccwrap_header.h ${ADD_OPTS}")
    else()
      message(WARNING "thirdparty/ccwrap directory is missing. For open watcom, run thirdparty/install_ccwap.bat")
      unset(TOOLCHAIN_USE_CCWRAP)
    endif()
endif()
if(NOT TOOLCHAIN_USE_CCWRAP)
    # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dnoexcept=throw()")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dnoexcept=")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dconstexpr=const")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Doverride=")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dfinal=")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dnullptr=0")
     #set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dchar16_t=unsigned\\ short -Dchar32_t=unsigned\\ int")
endif()

if(NOT CMAKE_CXX_FLAGS MATCHES "(^|[ \t])-xst([ \t]|$)")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -xst")
endif()

set(CMAKE_C_FLAGS_DEBUG            "-d2 -od -of+")
set(CMAKE_CXX_FLAGS_DEBUG          "-d2 -od -of+")
set(CMAKE_C_FLAGS_RELEASE          "-s -ot -d0 -dNDEBUG -zm")
set(CMAKE_CXX_FLAGS_RELEASE        "-s -ot -d0 -dNDEBUG -zm -zv")
set(CMAKE_C_FLAGS_MINSIZEREL       "-s -os -d0 -dNDEBUG -zm")
set(CMAKE_CXX_FLAGS_MINSIZEREL     "-s -os -d0 -dNDEBUG -zm -zv")
set(CMAKE_C_FLAGS_RELWITHDEBINFO   "-s -ot -d1 -dNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-s -ot -d1 -dNDEBUG")

set(CMAKE_EXE_LINKER_FLAGS_RELEASE    "option eliminate option vfremoval")
set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "option eliminate option vfremoval")

set(CMAKE_C_FLAGS   "${ADD_OPTS} ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${ADD_OPTS} ${CMAKE_CXX_FLAGS}")
