#set(TOOLCHAIN_NAME "watcom-pc98-dos16-s" CACHE STRING "Toolchain name")

set(CMAKE_SYSTEM_NAME "dos")
set(CMAKE_SYSTEM_PROCESSOR "I86")
set(CMAKE_C_COMPILER "wcl")
set(CMAKE_CXX_COMPILER "wcl")

set(CMAKE_WATCOM_RUNTIME_LIBRARY "SingleThreaded")

set(CMAKE_C_FLAGS   "-ms -k4000 -D__DOS__ -D__PC98__ -DCONS_USE_NEAR_TEXT_BUF ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "-ms -k4000 -D__DOS__ -D__PC98__ -DCONS_USE_NEAR_TEXT_BUF ${CMAKE_CXX_FLAGS}")

set(TOOLCHAIN_ADD_LIBS "pc98s" CACHE STRING "Watcom PC98 libraries")
