set(CMAKE_EXECUTABLE_SUFFIX ".exe")
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".exe")
set(CMAKE_EXECUTABLE_SUFFIX_C ".exe")
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".exe")

set(ADD_OPTS "-DUSE_OLD_COMPILER")
# set(TOOLCHAIN_USE_CCWRAP 1)
if(TOOLCHAIN_USE_CCWRAP)
    set(CCWRAP_DIR "${CMAKE_CURRENT_LIST_DIR}/../thirdparty/ccwrap")
    if(EXISTS "${CCWRAP_DIR}" AND IS_DIRECTORY "${CCWRAP_DIR}")
      set(ADD_OPTS "-I${CCWRAP_DIR}/watcom/ -I${CCWRAP_DIR}/ccwrap/ -DCCWRAP_NO_EXCEPTIONS -fi=${CCWRAP_DIR}/vc/ccwrap_header.h ${ADD_OPTS}")
    else()
      message(WARNING "thirdparty/ccwrap directory is missing. For open watcom, run thirdparty/install_ccwap.bat")
      unset(TOOLCHAIN_USE_CCWRAP)
    endif()
endif()
if(NOT TOOLCHAIN_USE_CCWRAP)
    # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dnoexcept=throw()")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dnoexcept=")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dconstexpr=const")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Doverride=")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dfinal=")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dnullptr=0")
     #set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dchar16_t=unsigned\\ short -Dchar32_t=unsigned\\ int")
endif()

set(CMAKE_C_FLAGS   "${ADD_OPTS} ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${ADD_OPTS} ${CMAKE_CXX_FLAGS}")
