#set(TOOLCHAIN_NAME "watcom-pc98-dos32" CACHE STRING "Toolchain name")

set(CMAKE_SYSTEM_NAME "dos")
set(CMAKE_SYSTEM_PROCESSOR "X86")
set(CMAKE_C_COMPILER "wcl386")
set(CMAKE_CXX_COMPILER "wcl386")

set(CMAKE_WATCOM_RUNTIME_LIBRARY "SingleThreaded")

set(CMAKE_C_FLAGS   "-D__DOS__ -D__PC98__ -DCONS_USE_NEAR_TEXT_BUF ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "-D__DOS__ -D__PC98__ -DCONS_USE_NEAR_TEXT_BUF ${CMAKE_CXX_FLAGS}")

set(TOOLCHAIN_ADD_LIBS "pc983r" CACHE STRING "Default Windows libraries")
